[tool.poetry]
name = "swmm_modflow_oss"
version = "0.1.0"
description = "Integration scheme for coupling SWMM and MODFLOW"
authors = [
    "tscheuch <tscheuch@uc.cl>",
    "jricci1 <jricci1@uc.cl>",
]

[tool.poetry.dependencies]
python = "^3.8"
flopy = "^3.3.4"
geopandas = "^0.10.2"
wheel = "^0.37.1"
setuptools = "^60.1.1"
twine = "^3.7.1"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
isort = "^5.10.1"


# LINTER CONFIGURATIONS
[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
