name: Linting Python code

on:
  pull_request:
    paths:
      - ".github/workflows/linters.yaml"
      - "**.py"
      # - ".pylintrc"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  pylinters:
    name: Run the linters
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry==1.2.2

      # Python is not required to run the linters.
      # We use this step for caching dependencies.
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      id: pysetup
      with:
        python-version: "3.9"
        cache: poetry

    - name: Install dependencies
      if: steps.pysetup.outputs.cache-hit == 'false'
      run: poetry install --only dev

    - name: Lint using all of our linters
      run: make --jobs black isort
