name: linters

on:
  pull_request:
    paths:
      - ".github/workflows/linters.yaml"
      - "**.py"
      # - ".pylintrc"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  pylinters:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        id: pysetup
        with:
          python-version: 3.9

      - name: Install Poetry
        run: make poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      # We aim to build a cache with the dependencies installed by Poetry.
      # In order to do that, we need to put them into the .venv directory.
      # Reference: https://python-poetry.org/docs/master/configuration
      - name: Set up Poetry cache
        uses: actions/cache@v3
        id: nicanor
        with:
          key: ${{ hashFiles('**/poetry.lock') }}-on-python-${{ steps.pysetup.outputs.python-version }}
          path: .venv

      - name: Install dependencies
        if: steps.nicanor.outputs.cache-hit != 'true'
        run: poetry install --only dev

      - name: Lint using all of our linters
        run: make --jobs black isort
